version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_demo
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
    ports:
      - "3306:3306"
    command: --local-infile=1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql-files
